apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mysql.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.mysql.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    spec:
      containers:
      - name: {{ template "mysql.name" . }}
        image: {{ .Values.mysql.deployment.image }}
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mysql.secrets" . }}
              key: db-password 
       
